name: development
on:
  pull_request:
    branches:
      - develop

  push:
    branches:
      - develop
jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.3
        env:
          POSTGRES_USER: db_user
          POSTGRES_PASSWORD: db_password
          POSTGRES_DB: db_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install Python dependencies
        run: python -m pip install -r requirements.txt

      - name: Run isort
        run: isort --check-only --profile=black .

      - name: Run black
        run: black --check .

      - name: Run flake8
        run: flake8 --ignore=E501,W503,F401 .

      - name: Unit Tests and Integration Tests
        env:
          DATABASE_TEST_URL: postgresql://db_user:db_password@localhost/db_test
        run: python -m flask tests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        id: docker_hub_auth
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask_template_image:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
